import Foundation
import XCTest

/// Fixtures are generated by `ios/scripts/generate_fixtures.py`, which runs
/// the repository's actual Python implementation (`voice_matcher.py`) on
/// deterministic synthetic voice audio. Regenerate them whenever the Python
/// reference changes.
func loadFixture<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
    let url = try XCTUnwrap(
        Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures"),
        "Missing fixture \(name).json — run ios/scripts/generate_fixtures.py"
    )
    return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
}

func assertClose(
    _ actual: [Double],
    _ expected: [Double],
    absoluteTolerance: Double,
    relativeTolerance: Double = 1e-6,
    _ message: String = "",
    file: StaticString = #filePath,
    line: UInt = #line
) {
    XCTAssertEqual(actual.count, expected.count, "\(message) length mismatch", file: file, line: line)
    for i in 0..<min(actual.count, expected.count) {
        let tolerance = max(absoluteTolerance, relativeTolerance * abs(expected[i]))
        XCTAssertEqual(
            actual[i], expected[i], accuracy: tolerance,
            "\(message) index \(i)", file: file, line: line
        )
    }
}
